version: '3'
services:
    app:
        build:
            context: ./.docker/app
            dockerfile: Dockerfile
        container_name: app
        image: app
        volumes:
            - '.:/var/www'
        networks:
            - cryptonet
        depends_on:
            - postgres
            - redis
    nginx:
        build:
            context: ./.docker/nginx
            dockerfile: Dockerfile
        container_name: nginx
        image: nginx
        volumes:
            - '.:/var/www'
        restart: always
        tty: true
        networks:
            - cryptonet
        ports:
            - "80:80"
        depends_on:
            - app
    postgres:
        image: postgres:alpine
        container_name: postgres
        restart: always
        environment:
            PGPASSWORD: 'postgres'
            POSTGRES_DB: 'crypto'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
        networks:
            - cryptonet
        ports:
            - "5432:5432"
    redis:
        image: redis
        networks:
            - cryptonet
networks:
    cryptonet:
        driver: bridge
